config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # гем Devise требует поместить это строку
  root to: "home#index"
  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  resources :articles do
    # resources :comments 
    resource :comments, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,length: { maximum: 140 }
  validates :text, presence: true 
  has_many :comments 

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :email, presence: true
    validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :authenticate_user!, only: [:new,:create]

    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        # render plain: params[:article].inspect
        @article = Article.new(article_params)
        if  @article.save
            redirect_to @article
        else
            render action: 'new'
        end
        
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else
            render action: 'edit'
        end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to @article
    end

    private

    def article_params
        params.require(:article).permit(:title, :text)
        
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!, only: [:create]

    def create
        @article = Article.find(params[:article_id])
        @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    private

    def comment_params
        params.require(:comment).permit(:author, :body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        # render plain: params[:contact].inspect
        @contact = Contact.new(contact_params)
        if @contact.valid?
            @contact.save
        else
            render action: 'new'
        end
    end

    private

    def contact_params
        params.require(:contact).permit(:email,:message)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def terms

    end

    def about 

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<h3>Thanks!</h3>
<p>Article has been created!</p> 
<p><%= link_to 'Show all articles', articles_path %></p>

app/views/articles/edit.html.erb
<%= form_with(model: @article, local: true, data: {turbo: false}, url: article_path(@article), method: :put) do |f|%>
    <p><%= f.label :title%></p>
    <p><%= f.text_field :title %></p>
     <p><%= f.label :text%></p>
    <p><%= f.text_area :text %></p>
    <p><%= f.submit 'Edit'%></p>
<% end %>

app/views/articles/index.html.erb
<h3>The articles list</h3>

<% @articles.each do |article|%>
    <h4><%= article.title%></h4>
    <p><%= article.text%></p>
    <p><%=  link_to 'Show', article_path(article)%></p>
    <p><%=  link_to 'Edit', edit_article_path(article)%></p>
    <p><%= button_to 'Delete',  article_path(article),  data:{turbo: false}, method: :delete%></p>
    <hr/>
    
<% end %>

app/views/articles/new.html.erb
<h3>New article<h3>

<%= form_with(model: @article, local: true, data: { turbo: false },  url: articles_path) do |f| %>
    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :text %><br/>
        <%= f.text_area :text %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/articles/show.html.erb
<h3><%= @article.title%></h3>
<p><%= @article.text%></p>

<% @article.comments.each do |comment|%>
    <p>
        <%= comment.author%>
    </p>
     <p>
        <%= comment.body%>
    </p>
    <hr/>
<% end%>

<%= form_with(model: [@article,@article.comments.build], local: true, data: {turbo: false}) do |f| %>
<p>
        <%= f.label :author %><br/>
        <%= f.text_field :author%>
    </p>

    <p>
        <%= f.label :body %><br/>
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end%>

app/views/contacts/create.html.erb
<h3>Thanks!</h3>

app/views/contacts/new.html.erb
<h3><%= t('contacts.contact_us') %></h3>
<%= form_with(model: @contact,local: true, data: {turbo: false}, url: contacts_path) do |f|%>
<p>
    <% @contact.errors.full_messages.each do |msg|%>
    <ul>
        <li><%= msg %>
    </ul>
    <% end %>
</p>
<p>
    <%= f.label :email%><br/>
    <%= f.text_field :email%>
</p>

<p>
    <%= f.label :message%><br/>
    <%= f.text_area :message%>
</p>

<%= f.submit 'Send message'%>


<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
  Hello, <%= current_user.username%>|<%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to 'Sign in', new_user_session_path %>
  <% end %>
  
 
<%# Эти две строки требует в настройках прописать devise %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h3>About:</h3>

app/views/pages/terms.html.erb
<h3>Terms:</h3>